### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by glutenfreepy** [imcf/rlm-prometheus#1]
Hi there,
Is it possible to run more than once instance of this on the same machine?  How would I do that?
Thank you :)

**Comment by ehrenfeu** [comment]
Hi @glutenfreepy - sorry for overlooking your question for so long 😦 🙏🏼 

You can simply create multiple services with different parameters (when using `systemd`) or manually launch multiple instances using different `.yaml` configuration files.

Just have a look at the corresponding lines in the example config file:

https://github.com/imcf/rlm-prometheus/blob/da1ee7f0e083c729b2230cc2b7d42e1f86ab23c9/resources/config-example.yaml#L8-L10

Hope this still helps!

**Comment by edatfuturedeluxe** [comment]
Yes that helps.  Thank you!
